### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nzk-tomo** [nzk-tomo/furima-31124#10]
# url
https://furima-31124.herokuapp.com/
# 認証ID&pass
ID: admin
pass: 2222
# 出品者用のメールアドレスとパスワード
email: sage@sage
pass: 111qqq
# 購入者用のメールアドレスとパスワード
email: age@age
pass: 111qqq
# 購入用カードの番号・期限・セキュリティコード
number: 4242424242424242
exp-m/y: 12/22
cvc : 123

**Comment by mo1015** [comment]
野月さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○商品詳細ページに「商品説明」が表示されるようにしましょう**

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by nzk-tomo** [comment]
修正しました

**Comment by mutorisa** [comment]
野月さん、再度ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by nzk-tomo** [comment]
ありがとうございます！
